### ISSUE TITLE
Messages from a same user should be grouped when they are consecutive

### ISSUE THREAD

**Issue by Pacane** [woven/woven#3]
When a user send multiple messages in a row, it should group them together instead of displaying them in separate message blocks.

**Comment by davenotik** [comment]
Oh, ah, hmm. I created, http://github.com/woven/tracker to track issues, separate of this repo because this repo isn't really cleaned up so as to be easily consumed, and soon I'll fork what we have here to a private repo for continued development. Thoughts?

**Comment by Pacane** [comment]
I don't think a readme file is really a way to track issues/features. If this repo goes private, your users need another to reach you for feature requests, bugs, etc. Since you said you're picky on the tools you use, I suggest you look into some external issue tracker and put a link to it somewhere.

**Comment by Pacane** [comment]
And the reasoning behind this is pretty simple. As soon as we get to discuss about it, log work, details, etc... the readme will be a mess. You need a simple way to track progress, manage a backlog and discuss about issues.

**Comment by davenotik** [comment]
Totally! https://github.com/woven/tracker has an issue tracker just like this.

https://github.com/woven/tracker/issues

**Comment by Pacane** [comment]
Oh my bad. I thought you wanted to manage this in a readme file. All good! :P

**Comment by Pacane** [comment]
cc: https://github.com/woven/tracker/issues/2
